### ISSUE TITLE
 Private method `require' called for Bundler:Module 

### ISSUE THREAD

**Issue by rankam** [MikaAK/Pintrest-Api#1]
Hello,

Thanks for this gem! When trying to use it I was getting the following error:

```
Private method `require' called for Bundler:Module 
```

Simply commenting out line 7 in lib/pintrest_api.rb resolved the issue. I rarely use Ruby so I'm not sure what the actual error is, but just wanted to let you know in case you were not aware.

Aaron

**Comment by MikaAK** [comment]
That line is to auto require gems from the gemfile via bundler. Do you have `gem bundler` installed?

**Comment by rankam** [comment]
Yes, I do now and everything works!
